#!/bin/bash

packageNamespace=$(kreadconfig5 --file="$PWD/package/metadata.desktop" --group="Desktop Entry" --key="X-KDE-PluginInfo-Name")
packageName="${packageNamespace##*.}" # Strip namespace (Eg: "org.kde.plasma.")
packageVersion=$(kreadconfig5 --file="$PWD/package/metadata.desktop" --group="Desktop Entry" --key="X-KDE-PluginInfo-Version")

find package/ -name *.qmlc -exec rm {} \;

### *.plasmoid
filename="${packageName}-${packageVersion}.plasmoid"


rm ${packageName}-*.plasmoid 2>/dev/null

./setversion

(cd package \
	&& zip -r $filename * \
	&& mv $filename ../$filename \
)

echo "[plasmoid] md5: $(md5sum $filename | awk '{ print $1 }')"
echo "[plasmoid] sha256: $(sha256sum $filename | awk '{ print $1 }')"

